//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataBaseParameters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataBaseParameters() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Resources.DataBaseParameters", typeof(DataBaseParameters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @definition.
        /// </summary>
        public static string definition {
            get {
                return ResourceManager.GetString("definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @diagramname.
        /// </summary>
        public static string diagramname {
            get {
                return ResourceManager.GetString("diagramname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @FullName.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @isAscending.
        /// </summary>
        public static string isAscending {
            get {
                return ResourceManager.GetString("isAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @message.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @new_diagramname.
        /// </summary>
        public static string new_diagramname {
            get {
                return ResourceManager.GetString("new_diagramname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @orderBy.
        /// </summary>
        public static string orderBy {
            get {
                return ResourceManager.GetString("orderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @owner_id.
        /// </summary>
        public static string owner_id {
            get {
                return ResourceManager.GetString("owner_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pageIndex.
        /// </summary>
        public static string pageIndex {
            get {
                return ResourceManager.GetString("pageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pageSize.
        /// </summary>
        public static string pageSize {
            get {
                return ResourceManager.GetString("pageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @price.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @text.
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @version.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @xml.
        /// </summary>
        public static string xml {
            get {
                return ResourceManager.GetString("xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @year.
        /// </summary>
        public static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
    }
}
