//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FieldText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FieldText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Resources.FieldText", typeof(FieldText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a car with ID of [{0}].
        /// </summary>
        public static string CarIdNotFoundErrorMessageFormat {
            get {
                return ResourceManager.GetString("CarIdNotFoundErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a car with name of [{0}].
        /// </summary>
        public static string CarNotFoundErrorMessageFormat {
            get {
                return ResourceManager.GetString("CarNotFoundErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        public static string Comma {
            get {
                return ResourceManager.GetString("Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialized = {0}{1}{1}Message={2}{1}{1}Stack Trace: {3}.
        /// </summary>
        public static string DeserializingErrorMessageFormat {
            get {
                return ResourceManager.GetString("DeserializingErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car name must be filled.
        /// </summary>
        public static string ErrorCarNameIsEmpty {
            get {
                return ResourceManager.GetString("ErrorCarNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car price must be a positive number.
        /// </summary>
        public static string ErrorCarPriceIsInvalid {
            get {
                return ResourceManager.GetString("ErrorCarPriceIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car year must be current or previous year.
        /// </summary>
        public static string ErrorCarYearIsInvalid {
            get {
                return ResourceManager.GetString("ErrorCarYearIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city not found.
        /// </summary>
        public static string ErrorCityNotFound {
            get {
                return ResourceManager.GetString("ErrorCityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name must be filled.
        /// </summary>
        public static string ErrorEmptyCityName {
            get {
                return ResourceManager.GetString("ErrorEmptyCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City of [{0}] is invalid.
        /// </summary>
        public static string ErrorInvalidCity {
            get {
                return ResourceManager.GetString("ErrorInvalidCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL of [{0}] is not reachable.
        /// </summary>
        public static string ErrorUrlNotReachable {
            get {
                return ResourceManager.GetString("ErrorUrlNotReachable", resourceCulture);
            }
        }
    }
}
