//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UtilityResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UtilityResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Resources.UtilityResources", typeof(UtilityResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json.
        /// </summary>
        public static string ApplicationTypeJson {
            get {
                return ResourceManager.GetString("ApplicationTypeJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class.
        /// </summary>
        public static string AttributeNameClass {
            get {
                return ResourceManager.GetString("AttributeNameClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onclick.
        /// </summary>
        public static string AttributeNameOnClick {
            get {
                return ResourceManager.GetString("AttributeNameOnClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onkeypress.
        /// </summary>
        public static string AttributeNameOnKeyPress {
            get {
                return ResourceManager.GetString("AttributeNameOnKeyPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string AttributeNameStyle {
            get {
                return ResourceManager.GetString("AttributeNameStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dd MMM} - {1:dd MMM}.
        /// </summary>
        public static string DateNameFormatString {
            get {
                return ResourceManager.GetString("DateNameFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} KB.
        /// </summary>
        public static string FileMaximumSizeInKb {
            get {
                return ResourceManager.GetString("FileMaximumSizeInKb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd MMM yyyy.
        /// </summary>
        public static string FormatDateDdMmmYyyy {
            get {
                return ResourceManager.GetString("FormatDateDdMmmYyyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd MMM yyyy HH:mm:ss.
        /// </summary>
        public static string FormatDateDdMmmYyyyHhMmSs {
            get {
                return ResourceManager.GetString("FormatDateDdMmmYyyyHhMmSs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        public static string FormatDateDdMmYyyy {
            get {
                return ResourceManager.GetString("FormatDateDdMmYyyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy HH:mm:ss.
        /// </summary>
        public static string FormatDateDdMmYyyyHhMmSs {
            get {
                return ResourceManager.GetString("FormatDateDdMmYyyyHhMmSs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy MM dd hh mm ss.
        /// </summary>
        public static string FormatDateYyyyMmDdHhMmSs {
            get {
                return ResourceManager.GetString("FormatDateYyyyMmDdHhMmSs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \w+([-+.&apos;]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*.
        /// </summary>
        public static string RegexEmail {
            get {
                return ResourceManager.GetString("RegexEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\d+$.
        /// </summary>
        public static string RegexRequiredDecimal {
            get {
                return ResourceManager.GetString("RegexRequiredDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31 Dec 9999.
        /// </summary>
        public static string SqlMaximumDate {
            get {
                return ResourceManager.GetString("SqlMaximumDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Jan 1753.
        /// </summary>
        public static string SqlMinimumDate {
            get {
                return ResourceManager.GetString("SqlMinimumDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt; {0}.
        /// </summary>
        public static string StringFormatAfterNewLine {
            get {
                return ResourceManager.GetString("StringFormatAfterNewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0}.
        /// </summary>
        public static string StringFormatAfterSpace {
            get {
                return ResourceManager.GetString("StringFormatAfterSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string TextAll {
            get {
                return ResourceManager.GetString("TextAll", resourceCulture);
            }
        }
    }
}
